name: Publish Make HDF Data

on:
  release:
    types: [published]

jobs:
  run_hdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install ase h5py pandas numpy
      - name: Run HDF function
        run: python /0_interlayer_energy/data/hdf_tools.py
      - name: Upload to S3
        env:
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_BUCKET_PATH: ${{ secrets. AWS_S3_BUCKET_PATH }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_USE_PATH_STYLE_ENDPOINT: true
        run: |
          aws s3 cp /0_interlayer_energy/qmc.hdf s3://$AWS_S3_BUCKET/$AWS_S3_BUCKET_PATH/${GITHUB_REF#refs/tags/}.hdf
